### ISSUE TITLE
Python Errors when launching 

### ISSUE THREAD

**Issue by marathon715** [mpetroff/qgsazimuth#31] opened 2023-09-19 15:11 UTC
I keep getting a Python error on launching the Azimuth and Distance Plugin. The issue is intermittent when launching for the first time in a session, but _always_ occurs when closing the plugin and trying to relaunch it in the same session. Uninstalling and reinstalling it usually fixes the issue, but that's kind of a pain. I'm not very experienced in Python, but Here is the error:

**2023-09-19T08:54:41     WARNING    Traceback (most recent call last):
              File "C:\Users/zasbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAzimuth\qgsAzimuth.py", line 190, in run
              self.loadConf() # get config data
              File "C:\Users/zasbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgsAzimuth\qgsAzimuth.py", line 1022, in loadConf
              self.pluginGui.move(position)
             TypeError: arguments did not match any overloaded call:
              move(self, QPoint): argument 1 has unexpected type 'QVariant'
              move(self, int, int): argument 1 has unexpected type 'QVariant'**

Here are all of my pertinent (I think) versions:

QGIS version
3.28.8-Firenze

Python version
3.9.5

OS version
Windows 10 Version 2009

I have also run the plugin on the QGIS Białowieża and Hertogenbosch releases, as well as Windows 11, and have had the same error. Any ideas? Thanks in advance for your help - your plugin is very useful for parcel mapping!

**Comment by mpetroff** [comment] 2023-09-23 22:07
I can't reproduce the issue, but it looks very similar to #22. I suspect it has something to do with where you dock / locate the plugin's GUI window.

I just committed a potential fix in 1d303424f3b0797c3ac6ef059910fee5109c6110.

Could you please download the [new version of `qgsAzimuth.py`](https://raw.githubusercontent.com/mpetroff/qgsazimuth/1d303424f3b0797c3ac6ef059910fee5109c6110/qgsAzimuth.py) and replace your `C:\Users\zasbh1\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgsAzimuth\qgsAzimuth.py` file with the new version to see if the fix works?

**Comment by marathon715** [comment] 2023-09-24 14:44
Interesting- I always drag the plugin window to a different monitor. I wonder if that has something to with it. I’ll test it and get back to you. Maybe the workaround is something as simple as re-docking the window before closing it.Thanks so much for following up - I use the plugin to verify the measurements on survey maps, and it’s absolutely invaluable for that purpose!- Stephen


On Sat, 23 Sep 2023 at 5:07 PM Matthew wrote:

I can't reproduce the issue, but it looks very similar to #22. I suspect it has something to do with where you dock / locate the plugin's GUI window.
I just committed a potential fix in 1d30342.
Could you please download the new version of qgsAzimuth.py and replace your C:Userszasbh1AppDataRoamingQGISQGIS3profilesdefaultpythonpluginsqgsAzimuthqgsAzimuth.py file with the new version to see if the fix works?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/mpetroff/qgsazimuth/issues/31#issuecomment-1732419471",
"url": "https://github.com/mpetroff/qgsazimuth/issues/31#issuecomment-1732419471",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by marathon715** [comment] 2023-10-04 16:17
That was it - as long as the plugin window stays on the same monitor as the rest of the application, the error does not occur. If the plugin window is is moved to a different monitor, and closed while displayed on that monitor, then a Python error is thrown on the next attempted launch.

**Comment by mpetroff** [comment] 2023-10-04 18:21
Did you update the Python file and see if my attempted fix worked?

**Comment by marathon715** [comment] 2023-10-11 14:22
Sorry it took so long to get back to you, but it works now - I can close the window on any monitor and it re-launches no problem. Thanks so much for working on the fix!!

**Comment by stantonium** [comment] 2023-12-28 18:14
This still happened to me when I re-installed the plugin.  After initial reinstall it works on relaunch, but not the first time after an new install.

**Comment by mpetroff** [comment] 2024-01-07 22:09
@stantonium I hadn't pushed a new release to the QGIS plugins repository, so unless you were manually installing the plugin from this Git repository, you wouldn't have had the fix. I just tagged and uploaded a new release (v0.9.17), so it should be available soon, once the update is approved by the QGIS repository moderators.

**Closed** 2024-02-15 01:11 UTC
Labels: bug
