### ISSUE TITLE
Lat/long starting point gigantic scaling 

### ISSUE THREAD

**Issue by plutext** [mpetroff/qgsazimuth#36] opened 2024-02-12 01:24 UTC
Steps to repro:
1. new project
2. set project crs to GDA2020 EPSG:7844
3. in the plugin, import:
```
angle=Bearing
heading=Magnetic
declination=9.775020223429575
dist_units=Feet
angle_unit=degree
startAt=148.54533;-34.95415;90
survey=Polygonal
[data]
270D 0';548.46;90;None;None
```

Scale needs to be 1:20M to see the entire line!

If instead I add a layer EPSG:3857 and choose a starting point "From Map", things work as expected.

Plugin version 0.9.18 of 10/1/24, QGIS 3.34.0

**Comment by mpetroff** [comment] 2024-02-13 01:53
This is a duplicate of #26.

The plugin doesn't work with degree-based coordinate systems such as EPSG:7844. It requires a planar projection, since it uses Euclidean geometry calculations.

**Closed by mpetroff** 2024-02-13 01:53 UTC

**Comment by plutext** [comment] 2024-02-14 18:58
It would be good if the plugin detected an attempt to use a degree-based coordinate system, warned the user, and said use a planar system instead, rather than returning broken output (ie appearing to work).  Half a day of my life I'll never get back.

**Comment by mpetroff** [comment] 2024-02-15 01:24
I just added such a check in c68bd3933040fbe888f13d5f29fe2f7cbb8b1997 and uploaded version v0.9.19 with it to the QGIS plugin repository (updates are generally approved within a day or two).

I also added a readme to this repository to make it clear that this plugin is primarily in maintenance mode. I was asked to take over maintenance after porting the plugin to QGIS 2 for a project I was working on more than a decade ago but haven't regularly used the plugin since. Thus, unless someone specifically asks like you did (and the change is small), no new features are added (although I guess this could also count as a bug fix, depending one's definition).
